Feature/co 831 implement meal card api
osu-mist/meal-card-api pull request #2
Opened 2017-07-05 23:14 UTC by adpextwindong

Removes the Skeleton Application
Adds the SQL, Mapper and general handling for the getByOSUID resource path.

2017-07-06 22:14 UTC, jaredkosanovic requested changes

2017-07-06 22:14 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/mealcard/resources/MealPlanResource.groovy
> +    @Path('{id: [0-9]+}/')
Unneeded '/' ?

2017-07-06 22:14 UTC, jaredkosanovic commented on gradle.properties
>  archivesBaseName=web-api-skeleton
Please update the archive base name

2017-07-06 22:14 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/mealcard/db/MealPlanDAO.groovy
> +                SELECT  OSU_ID,
For the API, we won't need to be selecting OSU_ID since we aren't returning that data as it's given from the DB.

2017-07-06 22:14 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/mealcard/resources/MealPlanResource.groovy
> +            return notFound().build()
I wasn't able to force a 404 from the API. I tried using my ID (when connecting it to the prod db) and it returned a 200 with an empty attributes. Doing the same sql query returns 0 rows.
```
{
  "links": {},
  "data": {
    "id": "932261339",
    "type": "balances",
    "attributes": [],
    "links": null
  }
}
```

2017-07-06 22:14 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/mealcard/resources/MealPlanResource.groovy
> +    private URI endpointUri
This variable wasn't used. Can we use it to create a self link in the api response? [Example method](https://github.com/osu-mist/academic-disciplines-api/blob/f27a83666a6bdf0fdfbacb64acfbd8bde4bdcabf/src/main/groovy/edu/oregonstate/mist/academicdisciplines/resources/AcademicDisciplinesResource.groovy#L72-L77)

Example response:
```
{
  "links": {},
  "data": {
    "id": "12345",
    "type": "balances",
    "attributes": [],
    "links": {
      "self":"https://api.oregonstate.edu/v1/diningbalances/12345"
    }
  }
}
```

2017-07-06 22:31 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/mealcard/mapper/MealPlanBalanceMapper.groovy
> +        String nowAsISO = dbDate.format(outputFormatter)
Could you change the variable name here? When I think of "now", I think of the current time. This variable holds the formatted lastUsedDate. Maybe something like `outputDate`?

2017-07-07 19:42 UTC, adpextwindong commented on src/main/groovy/edu/oregonstate/mist/mealcard/db/MealPlanDAO.groovy
> +                SELECT  OSU_ID,
Fixed

2017-07-07 19:48 UTC, adpextwindong commented on src/main/groovy/edu/oregonstate/mist/mealcard/mapper/MealPlanBalanceMapper.groovy
> +        String nowAsISO = dbDate.format(outputFormatter)
Fixed

2017-07-07 19:51 UTC, adpextwindong commented on src/main/groovy/edu/oregonstate/mist/mealcard/resources/MealPlanResource.groovy
> +    @Path('{id: [0-9]+}/')
Fixed

2017-07-07 21:41 UTC, adpextwindong commented on gradle.properties
>  archivesBaseName=web-api-skeleton
Fixed

2017-07-07 21:57 UTC, adpextwindong commented on src/main/groovy/edu/oregonstate/mist/mealcard/resources/MealPlanResource.groovy
> +            return notFound().build()
Fixed

2017-07-07 23:17 UTC, adpextwindong commented on src/main/groovy/edu/oregonstate/mist/mealcard/resources/MealPlanResource.groovy
> +    private URI endpointUri
Added.

2017-07-07 23:17 UTC, adpextwindong commented
Self Links handling for getByOSUID has been added.

2017-07-10 15:50 UTC, jaredkosanovic approved these changes

2017-07-10 17:27 UTC, floppyears requested changes

2017-07-10 17:27 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/mealcard/resources/MealPlanResource.groovy
> +class MealPlanResource extends Resource {
Let's add a couple of annotations here that most of our recent APIs are using: 
@PermitAll - allows us to specify that a user authentication is required for the endpoint.
@TypeChecked - tells the compiler that we want it to check types

2017-07-10 17:27 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/mealcard/db/MealPlanDAO.groovy
> +    Integer checkHealth()
Is there a HealthCheck class registered by the application?

2017-07-10 17:27 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/mealcard/mapper/MealPlanBalanceMapper.groovy
> +    private static DateTimeFormatter dbFormatter = DateTimeFormatter
Should these two be class level properties since they are only used in one method?

2017-07-10 17:27 UTC, floppyears commented on src/main/groovy/edu/oregonstate/mist/mealcard/mapper/MealPlanBalanceMapper.groovy
> +        def dbDate = ZonedDateTime.parse(rs.getString("LAST_USED_DATE") ,dbFormatter)
How about moving the date conversion to a separate method? Then line 33 could use that method. Let's also write a unit test for the date conversion method.

2017-07-10 21:04 UTC, adpextwindong commented on src/main/groovy/edu/oregonstate/mist/mealcard/resources/MealPlanResource.groovy
> +class MealPlanResource extends Resource {
Added

2017-07-10 21:10 UTC, adpextwindong commented on src/main/groovy/edu/oregonstate/mist/mealcard/db/MealPlanDAO.groovy
> +    Integer checkHealth()
Added

2017-07-10 22:48 UTC, adpextwindong commented on src/main/groovy/edu/oregonstate/mist/mealcard/mapper/MealPlanBalanceMapper.groovy
> +        def dbDate = ZonedDateTime.parse(rs.getString("LAST_USED_DATE") ,dbFormatter)
Refactored and added.

2017-07-10 22:59 UTC, floppyears approved these changes

2017-07-10 23:14 UTC, merged